---
title: "Log-Linear Migration Estimates with more covariates."
author: "Aysha"
date: "2024-05-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, comment=FALSE,fig.dim=c(18,12) ,out.width = "100%"}
library('rjags')
library('R2jags')
library(ggplot2)
library(tidyr)
library(plotly)
library(gridExtra)
library(grid)
z1 <- read.csv("data_ODAS_SC.csv", header = FALSE)
z2 <- read.csv("data_ODAS_RC.csv", header = FALSE)

zS <- array(as.matrix(z1), dim = c(18, 4, 4, 2, 7))
#dim(aperm(zS, c(5, 3, 2, 1, 4)))

zR <- array(as.matrix(z2), dim = c(18, 4, 4, 2, 7))
#dim(aperm(zR, c(5, 3, 2, 1, 4))) #test

# 0.1 denotes missing observation    
#zS <- extend_dim(zS,1, 3, 0.1)
#zR <- extend_dim(zR, 1, 2, 0.1)

#for (i in 1:32) {
 # zS[, i, i, , ] <- 0.1
 # zR[, i, i, , ] <- 0.1
#}

# Transform size to (TODAS) array
zS <- aperm(zS, c(5, 3, 2, 1, 4))
zR <- aperm(zR, c(5, 3, 2, 1, 4))


zS[zS==0.1] <- NA
zR[zR==0.1] <- NA

data_list <- list(
  zR = round(zR),
  zS = round(zS),
  nT = 7,
  nC = 4,
  #nC = 32,
  nA = 18,
  nS = 2 #,
  #totalO = 1, # index of total in origin
  #totalD = 1 # index of total in origin
)
model_jags_original_simplified_cov <- 
  "model {
  
  # Likelihood function 
  for (t in 1:nT) {
    for (a in 1:nA) {
      for (s in 1:nS) {
        for (o in 1:(nC-1)) {
          for (d in (o+1):nC) { #upper-right triangle
            zR[t, o, d, a, s] ~ dpois(lambda.R[t, o, d, a, s])   #lambda = v
            zS[t, o, d, a, s] ~ dpois(lambda.S[t, o, d, a, s])
          }
          for(d in 1:o){ #bottom-left triangle
            zR[t, o+1, d, a, s] ~ dpois(lambda.R[t, o+1, d, a, s])   #lambda = v
            zS[t, o+1, d, a, s] ~ dpois(lambda.S[t, o+1, d, a, s])
          }
        }
      }
    }
  }
  
  # Model
  for (t in 1:nT) {
    for (a in 1:nA) {
      for (s in 1:nS) {
        for (i in 1:nC){
           m[t, i, i, a, s] <- 0
           pi.prop[t, i, i, a, s]<-0
        }
        
        for (o in 1:(nC-1)) {
          for (d in (o+1):nC) { #upper-right triangle
            m[t, o, d, a, s] ~ dlnorm(alpha.da[d,a] +
                                      alpha.ds[d,s] +
                                      alpha.oa[o,a] +
                                      alpha.os[o,s] +
                                      alpha.ta[t,a] +
                                      alpha.ts[t,s] , tau.m) #+
                                      #alpha.ot[o,t] +
                                      #alpha.dt[d,t]
          
                                      
            lambda.R[t, o, d, a, s] ~ dlnorm(log(m[t, o, d, a, s]) + alpha.R[t, o, d], tau.R)
            lambda.S[t, o, d, a, s] ~ dlnorm(log(m[t, o, d, a, s]) + alpha.S[t, o, d], tau.S)
          }
          for(d in 1:o){  #bottom-left triangle
            m[t, o + 1, d, a, s] ~ dlnorm(alpha.da[d,a] +
                                          alpha.ds[d,s] +
                                          alpha.oa[o+1,a] +
                                          alpha.os[o+1,s] +
                                          alpha.ta[t,a] +
                                          alpha.ts[t,s] , tau.m) #+
                                          #alpha.ot[o+1,t] +
                                          #alpha.dt[d,t]
                                      
            lambda.R[t, o+1, d, a, s] ~ dlnorm(log(m[t, o+1, d, a, s]) + alpha.R[t, o+1, d], tau.R)
            lambda.S[t, o+1, d, a, s] ~ dlnorm(log(m[t, o+1, d, a, s]) + alpha.S[t, o+1, d], tau.S)
          }
        }
      }
    }
  }
  
  # Calculate m.sum and pi
  
  for (t in 1:nT) {
    for (o in 1:(nC-1)) {
      for (d in (o+1):nC) { #upper-right triangle
        m.sum[t, o, d] <- sum(m[t, o, d, 1:nA, 1:nS]) + 0.0001
        for (a in 1:nA) {
          for (s in 1:nS) {
            pi.prop[t, o, d, a, s] <- m[t, o, d, a, s] / m.sum[t, o, d]
          }
        }
      }
      for(d in 1:o){  #bottom-left triangle
        m.sum[t, o+1, d] <- sum(m[t, o+1, d, 1:nA, 1:nS]) + 0.0001
        for (a in 1:nA) {
          for (s in 1:nS) {
            pi.prop[t, o+1, d, a, s] <- m[t, o+1, d, a, s] / m.sum[t, o+1, d]
          }
        }
      }
    }
  }
  
  # Priors
  
  alpha.a[1] <- 0
  for (a in 2:nA) { 
    alpha.a[a] ~ dnorm(0, 1);
  }
  
  alpha.s[1] <- 0
  alpha.s[2] ~ dnorm(0, 1);

  tau.S ~ dgamma(0.001, 0.001)T(0.0001,20.00)
  tau.R ~ dgamma(0.001, 0.001)T(0.0001,20.00)
  tau.m ~ dgamma(0.001, 0.001)T(0.0001,20.00)
  
  ## interaction
  for (t in 1:nT) {
    for (o in 1:(nC-1)) {
      for (d in (o+1):nC) { #upper-right triangle
        alpha.R[t,o,d] ~ dnorm(0, 0.01)
        alpha.S[t,o,d] ~ dnorm(0, 0.01)
      }
      for(d in 1:o){  #bottom-left triangle
        alpha.R[t,o+1,d] ~ dnorm(0, 0.01)
        alpha.S[t,o+1,d] ~ dnorm(0, 0.01)
      }
    }
  }
  
  tau.alpha.da ~ dgamma(0.01, 0.01)T(0.0001,20.00)
  for (d in 1:nC) {
    for (a in 1:nA) {
      alpha.da[d,a] ~ dnorm(alpha.a[a], tau.alpha.da)
    }
  }
  
  tau.alpha.ds ~ dgamma(0.01, 0.01)T(0.0001,20.00)
  for (d in 1:nC) {
    for (s in 1:nS) {
      alpha.ds[d,s] ~ dnorm(alpha.s[s], tau.alpha.ds)
    }
  }
  
  tau.alpha.oa ~ dgamma(0.01, 0.01)T(0.0001,20.00)
  for (o in 1:nC) {
    for (a in 1:nA) {
      alpha.oa[o,a] ~ dnorm(alpha.a[a], tau.alpha.oa)
    }
  }
  
  tau.alpha.os ~ dgamma(0.01, 0.01)T(0.0001,20.00)
  for (o in 1:nC) {
    for (s in 1:nS) {
      alpha.os[o,s] ~ dnorm(alpha.s[s], tau.alpha.os)
    }
  }
  
  tau.alpha.ta ~ dgamma(0.01, 0.01)T(0.0001,20.00)
  for (t in 1:nT) {
    for (a in 1:nA) {
      alpha.ta[t,a] ~ dnorm(alpha.a[a], tau.alpha.ta)
    }
  }
  
  tau.alpha.ts ~ dgamma(0.01, 0.01)T(0.0001,20.00)
  for (t in 1:nT) {
    for (s in 1:nS) {
      alpha.ts[t,s] ~ dnorm(alpha.s[s], tau.alpha.ts)
    }
  }
  
  #tau.alpha.ot ~ dgamma(0.01, 0.01)T(0.0001,20.00)
  #for (o in 1:nC) {
    #for (t in 1:nT) {
      #alpha.ot[o,t] ~ dnorm(alpha.a[a], tau.alpha.oa)
    #}
  #}
  
  #tau.alpha.dt ~ dgamma(0.01, 0.01)T(0.0001,20.00)
  #for (d in 1:nC) {
    #for (t in 1:nT) {
      #alpha.os[o,s] ~ dnorm(alpha.s[s], tau.alpha.os)
    #}
  #}
}
"

# jags_model <- jags.model(textConnection(model_jags_original_simplified), data = data_list, n.chains = 1)
# jags_samples <- coda.samples(jags_model, n.iter = 1000)
writeLines(model_jags_original_simplified_cov, 'model_jags_original_simplified_cov.txt', useBytes = TRUE)

par_to_collect<-c("m","pi.prop",
                  "alpha.R","alpha.S",
                  'alpha.da','alpha.ds','alpha.oa','alpha.os','alpha.ta','alpha.ts',
                  "alpha.s","alpha.a",
                  "tau.R","tau.S","tau.m",
                  "τau.alpha.ds","τau.alpha.da","τau.alpha.os","τau.alpha.oa","tau.alpha.ta","tau.alpha.ts")

#mcmc_results <- res_jags_original_simplified$BUGSoutput$sims.list$pi.prop

#mcmc_results[,1,1,1,,]
##iter, time, orig, des, age, sex, value


mc.cores <- 4
a<-Sys.time()
res_jags_original_simplified_cov <- jags.parallel(
  data=data_list,
  parameters.to.save = par_to_collect,
  DIC = TRUE,
  model.file="model_jags_original_simplified_cov.txt",
  n.iter = 2000,
  n.thin = 5,
  jags.seed = 123,
  n.burnin = 500,
  n.chains = mc.cores,
  n.cluster = mc.cores)
#print(Sys.time()-a) # 2h on servers - n.iter = 2000.  n.burnin = 500, n.thin = 5 

save(file="res_jags_original_simplified_cov.rds",list="res_jags_original_simplified_cov")
year_mapping <- c(2009, 2010, 2011, 2012, 2013, 2014, 2015)
country_mapping <- c("AT", "FI", "NL", "SE")
valid_years <- 1:7
valid_countries <- 1:4
Age_Group <- c("00-04" ,  "05-09",  "10-14", "15-19"  , "20-24" , "25-29" , "30-34","35-39" ,"40-44",  "45-49" , "50-54" , "55-59" , "60-64"  , "65-69" , "70-74"  , "75-79"  ,"80-84" , "85+")
sexes <- c("F", "M")
Reported_Immigration <- data.frame()

for (a in 1:7) {
  for (b in 1:4) {
    for (c in 1:4) {
      for (d in 1:18) {
        for (e in 1:2) {
          #median_value <- median(zR[a, b, c, d, e])
          
          Reported_Immigration <- rbind(Reported_Immigration, data.frame(
            origin = country_mapping[b],
            destination = country_mapping[c],
            age = Age_Group[d],
            sex = sexes[e],
            year = year_mapping[a],
            value_im = zR[a, b, c, d, e]
          ))
        }
      }
    }
  }
}

#data sending country emigration
Reported_Emigration <- data.frame()

for (a in 1:7) {
  for (b in 1:4) {
    for (c in 1:4) {
      for (d in 1:18) {
        for (e in 1:2) {
          #median_value <- median(zR[a, b, c, d, e])
          
          Reported_Emigration <- rbind(Reported_Emigration, data.frame(
            origin = country_mapping[b],
            destination = country_mapping[c],
            age = Age_Group[d],
            sex = sexes[e],
            year = year_mapping[a],
            value_em = zS[a, b, c, d, e]
          ))
        }
      }
    }
  }
}
#print(head(Reported_Emigration,37:48))
#sum(sapply(par_to_collect[-c(1,2)], function(x) grepl(x,rownames(res_jags_original_simplified$BUGSoutput$summary))))

#num_rows <- length(valid_years)
#num_cols <- length(valid_countries) - 1

#gittest

#par(mfrow = c(num_rows, num_cols), mar = c(4, 4, 2, 1))
#num_cols <- length(valid_years) * length(valid_countries)
#par(mfrow = c(1, num_cols), mar = c(4, 4, 2, 1))
#current_col <- 1



library(gridExtra)

plot_list <- list()

for (year in valid_years) {
  plots_year <- list()
  for (country1 in valid_countries) {
    for (country2 in valid_countries) {
      if (country1 != country2) {
        data <- data.frame(
          Age = Age_Group,
          Male = apply(res_jags_original_simplified_cov$BUGSoutput$sims.list$m[, year, country1, country2, , 2], 2, median),
          Female = apply(res_jags_original_simplified_cov$BUGSoutput$sims.list$m[, year, country1, country2, , 1], 2, median),
          Male_sd = apply(res_jags_original_simplified_cov$BUGSoutput$sims.list$m[, year, country1, country2, , 2], 2, sd),
          Female_sd = apply(res_jags_original_simplified_cov$BUGSoutput$sims.list$m[, year, country1, country2, , 1], 2,sd)
        )
        data_long <- data %>%
          pivot_longer(cols = c(Male, Female), names_to = "Gender", values_to = "Proportion") %>%
          separate(Gender, into = c("Gender", "SD"), sep = "_") %>%
          mutate(SD = ifelse(Gender == "Male", Male_sd, Female_sd)) %>%
          select(-Male_sd, -Female_sd)
        
        im_data <- Reported_Immigration %>%
          filter(year == year_mapping[year], origin == country_mapping[country1], destination == country_mapping[country2]) %>%
          select(age, sex, value_im) %>%
          rename(Proportion = value_im)
        
        em_data <- Reported_Emigration %>%
          filter(year == year_mapping[year], origin == country_mapping[country1], destination == country_mapping[country2]) %>%
          select(age, sex, value_em) %>%
          rename(Proportion = value_em)
        #print(head(em_data,10))
        
        # Create the ggplot object
        p <- ggplot(data_long, aes(x = Age, y = Proportion, color = Gender)) +
          geom_line() +
          geom_point() +
          geom_errorbar(aes(ymin = Proportion - (0.05)*SD, ymax = Proportion + (0.05)*SD), width = 0.4) +
          geom_line(data = im_data, aes(x = age, y = Proportion, color = sex), linetype = "dashed", color = "green") +
          geom_line(data = em_data, aes(x = age, y = Proportion, color = sex), linetype = "dotted", color = "red") +
          labs(x = "Age", y = "Migration Flow", 
               title = paste(
                             "From", country_mapping[country1], 
                             "to", country_mapping[country2])) +
          scale_color_manual(values = c("Male" = "blue", "Female" = "pink")) +
          theme_minimal()
        
        plots_year[[length(plots_year) + 1]] <- p
      }
    }
  }

  #plot_row <- do.call(grid.arrange, c(plots_year, ncol = 3))
   plot_row_with_heading <- gridExtra::grid.arrange(grobs = plots_year, top = textGrob(label = paste("Year", year_mapping[year]), gp = gpar(fontsize = 20)), ncol = 3)
  
  plot_list[[length(plot_list) + 1]] <- plot_row_with_heading
}


#final_plot <- do.call(grid.arrange, c(plot_list, ncol = 1))

#print(final_plot)


```

